=== tranquang9a1/xml-spring2015/trunk/Crawler/src/com/crawler/xml/mangaSchema.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns = "http://www.fpt.edu.vn" 
           targetNamespace="http://www.fpt.edu.vn">
    <xs:element name="stories">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="story" type="StoryType" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="StoryType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="author" type="xs:string"></xs:element>
            <xs:element name="status" type="xs:string"></xs:element>
            <xs:element name="source" type="xs:string"></xs:element>
            <xs:element name="type" type="xs:string" maxOccurs="unbounded"></xs:element>
            <xs:element name="image" type="xs:string"></xs:element>
            <xs:element name="description" type="xs:string"></xs:element>
            <xs:element name="newest_chap" type="xs:string"></xs:element>
            <xs:element name="update_date" type="xs:long"></xs:element>
            <xs:element name="chapters" type="chapter"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="chapter">
        <xs:sequence>
            <xs:element name="chapter" type="chapterType" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="chapterType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="data" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== tranquang9a1/xml-spring2015/trunk/Crawler/src/com/crawler/xml/story.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<stories xmlns ="http://www.fpt.edu.vn"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation="http://www.fpt.edu.vn mangaSchema.xsd">
    <story>
        <name>My Life, My Daisy</name>
        <author>Quang Tran</author>
        <status>On Going</status>
        <source>http://www.izmanga.com</source>
        <type>Comic, Manga, Comedy, Action, Drama, Fantasy</type>
        <image>http://izmanga.com/files/images/161264.jpg</image>
        <description>Khi còn nhỏ, Luffy, nhân vật chính của chúng ta, ước mơ trở thành Vua Hải Tặc. Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su, nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc của mình ra khơi tìm kiếm kho báu One Piece, kho báu vĩ đại nhất trên thế giới</description>
        <newest_chap>Chap 14</newest_chap>
        <update_date>1422371650</update_date>
        <chapters>
            <chapter>
                <name>Chapter 14</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 13</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 12</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
        </chapters>
        
    </story>
    <story>
        <name>My Life, My Daisy</name>
        <author>Quang Tran</author>
        <status>On Going</status>
        <source>http://www.izmanga.com</source>
        <type>Comic, Manga, Comedy, Action, Drama, Fantasy</type>
        <image>http://izmanga.com/files/images/161264.jpg</image>
        <description>Khi còn nhỏ, Luffy, nhân vật chính của chúng ta, ước mơ trở thành Vua Hải Tặc. Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su, nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc của mình ra khơi tìm kiếm kho báu One Piece, kho báu vĩ đại nhất trên thế giới</description>
        <newest_chap>Chap 14</newest_chap>
        <update_date>1422371650</update_date>
        <chapters>
            <chapter>
                <name>Chapter 14</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 13</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 12</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
        </chapters>
        
    </story>
    <story>
        <name>My Life, My Daisy</name>
        <author>Quang Tran</author>
        <status>On Going</status>
        <source>http://www.izmanga.com</source>
        <type>Comic, Manga, Comedy, Action, Drama, Fantasy</type>
        <image>http://izmanga.com/files/images/161264.jpg</image>
        <description>Khi còn nhỏ, Luffy, nhân vật chính của chúng ta, ước mơ trở thành Vua Hải Tặc. Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su, nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc của mình ra khơi tìm kiếm kho báu One Piece, kho báu vĩ đại nhất trên thế giới</description>
        <newest_chap>Chap 14</newest_chap>
        <update_date>1422371650</update_date>
        <chapters>
            <chapter>
                <name>Chapter 14</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 13</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
            <chapter>
                <name>Chapter 12</name>
                <data>http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg|http://izmanga.com/files/images/161264.jpg</data>
            </chapter>
        </chapters>
        
    </story>
    
</stories>
